### ISSUE TITLE
`#pragma once` gets ignored resulting in `error: redefinition of blah`

### ISSUE THREAD

**Issue by prime31** [xoofx/CppAst#11]
First off, awesome work on this! It's going to save me crazy amounts of time. Many thanks!

I'm running into an issue while trying to parse a library where the `#pragma once` is ignored and it results in duplicate struct/enum definitions due to multiple files including one other.

A simple example given these files passed to `CppParser.ParseFiles`:
```
matrix.h
vector.h
graphics.h -> includes matrix.h and vector.h
```

All the headers are protected by a `#pragma once` but this seems to get ignored and the types get added multiple times causing an error.

Is there any way around this behavior?

**Comment by xoofx** [comment]
I have added a test to commit 0b053fce9531612ac6f95e5938a2a9834b09355f and it is not reproducible. Are you sure that you don't have something else going on?

**Comment by prime31** [comment]
Hmm. The test looks very similar to what I am parsing. For reference, here is one of the folders:

https://github.com/Kode/Kinc/tree/master/Sources/kinc/graphics4

The headers in there include each other and some of the files in the math folder one directory down. If I pass in all the headers I get the duplicated types.

I have found a workaround which is to:
- pass all the headers in
-  see what dupe error pops up and don’t pass in that header
- repeat steps 1 and 2 until no more errors

**Comment by xoofx** [comment]
Closing as not reproducible on unit tests.
