### ISSUE TITLE
Expose statements as classes

### ISSUE THREAD

**Issue by Piruzzolo** [xoofx/CppAst#7]
If you plan to extend the project to .c/.cpp files too, i'd suggest to expose statements too
For instance, for an `IfStatement` , it would expose its Condition block, its `IfTrue` block and its `Else`

```C#
class IfStatement : Statement
{
    IfStatement(Block condition, Block trueCond, Block elseBlock) {
        this.condition = condition;
        this.trueCond = trueCond;
        this.elseBlock = trueCond;
    }

    public bool hasElse {get; set;};

    public Statement condition {get; set;};
    public Block trueCond {get; set;};
    public Block elseBlock {get; set;}; // null if not present
    
}
```

Something like this. Note that `Block` could be a `Statement` e.g. when we have a single statement IF (without brackets).

**Comment by xoofx** [comment]
CppAst is meant only to expose header files without function bodies. There is no plan to expose the entire C++ Ast (specially because CppAst relies on libclang which has pretty limited support in many areas)
